# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7e799242bd389a1214fc875d1666eb1037943c3eb87d4cbddd4fd202672a0c4d3f114354f9659c230268f5777c0f95731b688a399a737ab6ab3148292ae5894
  app_id: 935457427990-q5144mn1vh3soagdb5pm3tb60on1n1cl.apps.googleusercontent.com
  app_secret: QuaLcVh6YibDbJJl9AES3frI
test:
  secret_key_base: f082ea1bd9c9433637150e9643830c47b1417fdde421656b97059f0bb97acaec3e36a1ea5afee96267ae8eebfa0397648dd4d5e4bab74368abe64f6232617927

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:


